name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: node

  publish:
    needs: release-please
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.release_created
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm ci --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish
